<div class="clearfix">
    <div class="alert alert-danger" role="alert">
        <?php _e('Please do not use ads or ad word on image name or image path or your codes, if you or your user browsers have adblock add-on, your ads hide by it'); ?>
    </div>
    <?php if (!empty($list1)) { ?>
        <h3><?php _e('List of active ads for web'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list1 as $item) { ?>
                <tr>
                    <td><?php echo $this->escape($item['id']); ?></td>
                    <td clas="clearfix">
                        <div class="col-md-9">
                            <h4><?php echo $this->escape($item['title']); ?></h4>
                            <div class="row">
                                <div class="col-md-6">
                                    <p><strong><?php _e('Publish time'); ?></strong>
                                        : <?php echo $this->escape($item['time_publish']); ?></p>
                                    <p><strong><?php _e('Expire time'); ?></strong>
                                        : <?php echo $this->escape($item['time_expire']); ?></p>
                                </div>
                                <div class="col-md-6">
                                    <p><strong><?php _e('View'); ?></strong> : <?php echo $this->escape($item['view']); ?>
                                    </p>
                                    <p><strong><?php _e('Click'); ?></strong> : <?php echo $this->escape($item['click']); ?>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" value="<?php echo Pi::url($this->url('ads', [
                                            'module'     => $module,
                                            'controller' => 'index',
                                            'action'     => 'click',
                                            'id'         => $item['id'],
                                            'device'     => $item['device'],
                                        ])); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <?php if ($item['type'] == 'image') { ?>
                                <img src="<?php echo $this->escape($item['image_url']); ?>"
                                     alt="<?php echo $this->escape($item['title']); ?>"
                                     class="img-responsive img-thumbnail">
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', [
                            'action' => 'update',
                            'id'     => $item['id'],
                            'type'   => $item['type'],
                            'device' => $item['device'],
                        ]); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>

    <?php if (!empty($list2)) { ?>
        <h3><?php _e('List of active ads for mobile'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list2 as $item) { ?>
                <tr>
                    <td><?php echo $this->escape($item['id']); ?></td>
                    <td clas="clearfix">
                        <div class="col-md-9">
                            <h4><?php echo $this->escape($item['title']); ?></h4>
                            <div class="col-md-6">
                                <p><strong><?php _e('Publish time'); ?></strong>
                                    : <?php echo $this->escape($item['time_publish']); ?></p>
                                <p><strong><?php _e('Expire time'); ?></strong>
                                    : <?php echo $this->escape($item['time_expire']); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p><strong><?php _e('View'); ?></strong> : <?php echo $this->escape($item['view']); ?>
                                </p>
                                <p><strong><?php _e('Click'); ?></strong> : <?php echo $this->escape($item['click']); ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <?php if ($item['type'] == 'image') { ?>
                                <img src="<?php echo $this->escape($item['image_url']); ?>"
                                     alt="<?php echo $this->escape($item['title']); ?>"
                                     class="img-responsive img-thumbnail">
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', [
                            'action' => 'update',
                            'id'     => $item['id'],
                            'type'   => $item['type'],
                            'device' => $item['device'],
                        ]); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>

    <?php if (!empty($list3)) { ?>
        <h3><?php _e('List of nonpublish ads'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list3 as $item) { ?>
                <tr>
                    <td><?php echo $this->escape($item['id']); ?></td>
                    <td clas="clearfix">
                        <div class="col-md-9">
                            <h4><?php echo $this->escape($item['title']); ?></h4>
                            <div class="col-md-6">
                                <p><strong><?php _e('Publish time'); ?></strong>
                                    : <?php echo $this->escape($item['time_publish']); ?></p>
                                <p><strong><?php _e('Expire time'); ?></strong>
                                    : <?php echo $this->escape($item['time_expire']); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p><strong><?php _e('View'); ?></strong> : <?php echo $this->escape($item['view']); ?>
                                </p>
                                <p><strong><?php _e('Click'); ?></strong> : <?php echo $this->escape($item['click']); ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <?php if ($item['type'] == 'image') { ?>
                                <img src="<?php echo $this->escape($item['image_url']); ?>"
                                     alt="<?php echo $this->escape($item['title']); ?>"
                                     class="img-responsive img-thumbnail">
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', [
                            'action' => 'update',
                            'id'     => $item['id'],
                            'type'   => $item['type'],
                            'device' => $item['device'],
                        ]); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>

    <?php if (!empty($list4)) { ?>
        <h3><?php _e('List of expire ads'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list4 as $item) { ?>
                <tr>
                    <td><?php echo $this->escape($item['id']); ?></td>
                    <td clas="clearfix">
                        <div class="col-md-9">
                            <h4><?php echo $this->escape($item['title']); ?></h4>
                            <div class="col-md-6">
                                <p><strong><?php _e('Publish time'); ?></strong>
                                    : <?php echo $this->escape($item['time_publish']); ?></p>
                                <p><strong><?php _e('Expire time'); ?></strong>
                                    : <?php echo $this->escape($item['time_expire']); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p><strong><?php _e('View'); ?></strong> : <?php echo $this->escape($item['view']); ?>
                                </p>
                                <p><strong><?php _e('Click'); ?></strong> : <?php echo $this->escape($item['click']); ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <?php if ($item['type'] == 'image') { ?>
                                <img src="<?php echo $this->escape($item['image_url']); ?>"
                                     alt="<?php echo $this->escape($item['title']); ?>"
                                     class="img-responsive img-thumbnail">
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', [
                            'action' => 'update',
                            'id'     => $item['id'],
                            'type'   => $item['type'],
                            'device' => $item['device'],
                        ]); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>

    <?php if (!empty($list5)) { ?>
        <h3><?php _e('List of offline ads'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list5 as $item) { ?>
                <tr>
                    <td><?php echo $this->escape($item['id']); ?></td>
                    <td clas="clearfix">
                        <div class="col-md-9">
                            <h4><?php echo $this->escape($item['title']); ?></h4>
                            <div class="col-md-6">
                                <p><strong><?php _e('Publish time'); ?></strong>
                                    : <?php echo $this->escape($item['time_publish']); ?></p>
                                <p><strong><?php _e('Expire time'); ?></strong>
                                    : <?php echo $this->escape($item['time_expire']); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p><strong><?php _e('View'); ?></strong> : <?php echo $this->escape($item['view']); ?>
                                </p>
                                <p><strong><?php _e('Click'); ?></strong> : <?php echo $this->escape($item['click']); ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <?php if ($item['type'] == 'image') { ?>
                                <img src="<?php echo $this->escape($item['image_url']); ?>"
                                     alt="<?php echo $this->escape($item['title']); ?>"
                                     class="img-responsive img-thumbnail">
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', [
                            'action' => 'update',
                            'id'     => $item['id'],
                            'type'   => $item['type'],
                            'device' => $item['device'],
                        ]); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>
</div>