<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of active ads for web'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $item) { ?>
                <tr>
                    <td><?php echo $this->escape($item['id']); ?></td>
                    <td><?php echo $this->escape($item['title']); ?></td>
                    <td>
                        <span class="badge badge-primary"><?php _e('Height'); ?>
                            : <?php echo $this->escape($item['height']); ?></span>
                        <span class="badge badge-primary"><?php _e('Width'); ?>
                            : <?php echo $this->escape($item['width']); ?></span>
                    </td>
                    <td><a class="btn btn-primary" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $item['id']]); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit'); ?></a></td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>
</div>