<div class="ads">
	<p>
	   <a class="btn" title="<?php _e('New Category'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="icon-file"></i> <?php _e('New Category'); ?></a>
	</p>
	<?php if (!empty($list)) { ?>
	<h3><?php _e('List of active ads for web'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Information'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $item) { ?>
		<tr>
			<td><?php echo $this->escape($item['id']); ?></td>
			<td><?php echo $this->escape($item['title']); ?></td>
			<td>
				<span class="label label-info"> Height : <?php echo $this->escape($item['height']); ?></span>
				<span class="label label-info"> Width : <?php echo $this->escape($item['width']); ?></span>
			</td>
			<td><a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $item['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a></td>
		</tr>
		<?php } ?>
	</table>	
	<?php } ?>
</div>