<div class="clearfix">
	<h3><?php _e('Ads click logs'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Ads'); ?></th>
			<th><?php _e('Device'); ?></th>
			<th><?php _e('User'); ?></th>
			<th><?php _e('Ip'); ?></th>
			<th><?php _e('Time'); ?></th>

		</tr>
		<?php foreach($list as $log) { ?>
		<tr>
			<td><?php echo $this->escape($log['id']); ?></td>
			<td><?php echo $this->escape($log['propaganda']); ?></td>
			<td><?php echo $this->escape($log['device']); ?></td>
			<td><?php echo $this->escape($log['uid']); ?></td>
			<td><?php echo $this->escape($log['ip']); ?></td>
			<td><?php echo $this->escape($log['time_create']); ?></td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>