<?php if (!empty($block['resources'])) { ?>
<div class="ads-block-random clearfix">
	<?php foreach ($block['resources'] as $resources) { ?>
	<div class="ads-item center-block">
		<a class="thumbnail" rel="external nofollow" target="_blank" title="<?php echo $resources['title']; ?>" href="<?php echo $resources['back_url']; ?>">
			<img src="<?php echo $resources['image_url']; ?>" alt="<?php echo $resources['title']; ?>" />
		</a>
	</div>
	<?php } ?>
</div>
<?php } ?>