<script type="text/javascript" src="<?php echo pi::url('static/vendor/jquery/jquery.min.js') ?>"></script>
<script type="text/javascript">
$(document).ready(function() {
        setTimeout(function() { 
            window.open('<?php echo $url; ?>', '_self');
        }, 0);
    });
</script>
<!-- <form action="<?php echo $url; ?>" method="get" name="openAds"></form>
<script>document.openAds.submit();</script> -->